logging:
  level:
    org:
      springframework:
        hibernate:
          resource:
            transaction: debug
        orm:
          jpa:
            JpaTransactionManager: debug
        jdbc:
          datasource:
            DataSourceTransactionManager: debug
        transaction:
          interceptor: debug